name: Deploy

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v2.3.1

      - name: 💻 Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: 🧶 Installing Packages
        run: yarn --ignore-engines

      - name: ⌛ Build App
        run: yarn export

      - name: 🚀 Deploy
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          commit_message: '📌 Deploy'
          target_branch: pages
          build_dir: out
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
