name: Export

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
      - name: Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Installing my packages
        run: yarn --ignore-engines

      - name: Build App
        run: yarn export

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          BRANCH: pages
          FOLDER: out
